/**
 * This class is generated by jOOQ
 */
package com.trunksoft.chat.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMessageTemplateRecord extends org.jooq.impl.UpdatableRecordImpl<com.trunksoft.chat.jooq.tables.records.ChatMessageTemplateRecord> implements org.jooq.Record12<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1380116437;

	/**
	 * Setter for <code>chatdb.chat_message_template.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.account_id</code>.
	 */
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.last_updated</code>.
	 */
	public void setLastUpdated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.last_updated</code>.
	 */
	public java.sql.Timestamp getLastUpdated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.primary_industry</code>.
	 */
	public void setPrimaryIndustry(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.primary_industry</code>.
	 */
	public java.lang.String getPrimaryIndustry() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.sample</code>.
	 */
	public void setSample(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.sample</code>.
	 */
	public java.lang.String getSample() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.secondary_industry</code>.
	 */
	public void setSecondaryIndustry(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.secondary_industry</code>.
	 */
	public java.lang.String getSecondaryIndustry() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.template_id</code>.
	 */
	public void setTemplateId(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.template_id</code>.
	 */
	public java.lang.String getTemplateId() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>chatdb.chat_message_template.type</code>.
	 */
	public void setType(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>chatdb.chat_message_template.type</code>.
	 */
	public java.lang.Integer getType() {
		return (java.lang.Integer) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.LAST_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.PRIMARY_INDUSTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.SAMPLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.SECONDARY_INDUSTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.TEMPLATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getLastUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getPrimaryIndustry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getSample();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getSecondaryIndustry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getTemplateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getType();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChatMessageTemplateRecord
	 */
	public ChatMessageTemplateRecord() {
		super(com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE);
	}

	/**
	 * Create a detached, initialised ChatMessageTemplateRecord
	 */
	public ChatMessageTemplateRecord(java.lang.Long id, java.lang.Long version, java.lang.Long accountId, java.lang.String content, java.sql.Timestamp dateCreated, java.sql.Timestamp lastUpdated, java.lang.String primaryIndustry, java.lang.String sample, java.lang.String secondaryIndustry, java.lang.String templateId, java.lang.String title, java.lang.Integer type) {
		super(com.trunksoft.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE);

		setValue(0, id);
		setValue(1, version);
		setValue(2, accountId);
		setValue(3, content);
		setValue(4, dateCreated);
		setValue(5, lastUpdated);
		setValue(6, primaryIndustry);
		setValue(7, sample);
		setValue(8, secondaryIndustry);
		setValue(9, templateId);
		setValue(10, title);
		setValue(11, type);
	}
}
