/**
 * This class is generated by jOOQ
 */
package com.trunksoft.chat.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatTemplateMessageRecord extends org.jooq.impl.UpdatableRecordImpl<com.trunksoft.chat.jooq.tables.records.ChatTemplateMessageRecord> implements org.jooq.Record16<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 998781943;

	/**
	 * Setter for <code>chatdb.chat_template_message.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.account_id</code>.
	 */
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.data_json</code>.
	 */
	public void setDataJson(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.data_json</code>.
	 */
	public java.lang.String getDataJson() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.errcode</code>.
	 */
	public void setErrcode(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.errcode</code>.
	 */
	public java.lang.Integer getErrcode() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.errmsg</code>.
	 */
	public void setErrmsg(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.errmsg</code>.
	 */
	public java.lang.String getErrmsg() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.from_user_id</code>.
	 */
	public void setFromUserId(java.lang.Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.from_user_id</code>.
	 */
	public java.lang.Long getFromUserId() {
		return (java.lang.Long) getValue(7);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.last_updated</code>.
	 */
	public void setLastUpdated(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.last_updated</code>.
	 */
	public java.sql.Timestamp getLastUpdated() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.msg_time</code>.
	 */
	public void setMsgTime(java.lang.Long value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.msg_time</code>.
	 */
	public java.lang.Long getMsgTime() {
		return (java.lang.Long) getValue(9);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.msgid</code>.
	 */
	public void setMsgid(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.msgid</code>.
	 */
	public java.lang.Long getMsgid() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.status</code>.
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.status</code>.
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.template_id</code>.
	 */
	public void setTemplateId(java.lang.Long value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.template_id</code>.
	 */
	public java.lang.Long getTemplateId() {
		return (java.lang.Long) getValue(12);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.to_user_id</code>.
	 */
	public void setToUserId(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.to_user_id</code>.
	 */
	public java.lang.Long getToUserId() {
		return (java.lang.Long) getValue(13);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.type</code>.
	 */
	public void setType(java.lang.Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.type</code>.
	 */
	public java.lang.Integer getType() {
		return (java.lang.Integer) getValue(14);
	}

	/**
	 * Setter for <code>chatdb.chat_template_message.url</code>.
	 */
	public void setUrl(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>chatdb.chat_template_message.url</code>.
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.DATA_JSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.ERRCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.ERRMSG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field8() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.FROM_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.LAST_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field10() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.MSG_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.MSGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field13() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.TEMPLATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.TO_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field15() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDataJson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getErrcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getErrmsg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value8() {
		return getFromUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getLastUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value10() {
		return getMsgTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getMsgid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value13() {
		return getTemplateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getToUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value15() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getUrl();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChatTemplateMessageRecord
	 */
	public ChatTemplateMessageRecord() {
		super(com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE);
	}

	/**
	 * Create a detached, initialised ChatTemplateMessageRecord
	 */
	public ChatTemplateMessageRecord(java.lang.Long id, java.lang.Long accountId, java.lang.String content, java.lang.String dataJson, java.sql.Timestamp dateCreated, java.lang.Integer errcode, java.lang.String errmsg, java.lang.Long fromUserId, java.sql.Timestamp lastUpdated, java.lang.Long msgTime, java.lang.Long msgid, java.lang.Integer status, java.lang.Long templateId, java.lang.Long toUserId, java.lang.Integer type, java.lang.String url) {
		super(com.trunksoft.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE);

		setValue(0, id);
		setValue(1, accountId);
		setValue(2, content);
		setValue(3, dataJson);
		setValue(4, dateCreated);
		setValue(5, errcode);
		setValue(6, errmsg);
		setValue(7, fromUserId);
		setValue(8, lastUpdated);
		setValue(9, msgTime);
		setValue(10, msgid);
		setValue(11, status);
		setValue(12, templateId);
		setValue(13, toUserId);
		setValue(14, type);
		setValue(15, url);
	}
}
