/**
 * This class is generated by jOOQ
 */
package com.trunksoft.chat.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMaterialRecord extends org.jooq.impl.UpdatableRecordImpl<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord> implements org.jooq.Record22<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -364468301;

	/**
	 * Setter for <code>chatdb.chat_material.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>chatdb.chat_material.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>chatdb.chat_material.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.account_id</code>.
	 */
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>chatdb.chat_material.cost_time</code>.
	 */
	public void setCostTime(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.cost_time</code>.
	 */
	public java.lang.Long getCostTime() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>chatdb.chat_material.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>chatdb.chat_material.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>chatdb.chat_material.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>chatdb.chat_material.errcode</code>.
	 */
	public void setErrcode(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.errcode</code>.
	 */
	public java.lang.Integer getErrcode() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>chatdb.chat_material.errmsg</code>.
	 */
	public void setErrmsg(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.errmsg</code>.
	 */
	public java.lang.String getErrmsg() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>chatdb.chat_material.last_updated</code>.
	 */
	public void setLastUpdated(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.last_updated</code>.
	 */
	public java.sql.Timestamp getLastUpdated() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>chatdb.chat_material.material_type</code>.
	 */
	public void setMaterialType(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.material_type</code>.
	 */
	public java.lang.Integer getMaterialType() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>chatdb.chat_material.media_id</code>.
	 */
	public void setMediaId(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.media_id</code>.
	 */
	public java.lang.String getMediaId() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>chatdb.chat_material.media_size</code>.
	 */
	public void setMediaSize(java.lang.Long value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.media_size</code>.
	 */
	public java.lang.Long getMediaSize() {
		return (java.lang.Long) getValue(12);
	}

	/**
	 * Setter for <code>chatdb.chat_material.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>chatdb.chat_material.path</code>.
	 */
	public void setPath(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.path</code>.
	 */
	public java.lang.String getPath() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>chatdb.chat_material.class</code>.
	 */
	public void setClass_(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.class</code>.
	 */
	public java.lang.String getClass_() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>chatdb.chat_material.time</code>.
	 */
	public void setTime(java.lang.Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.time</code>.
	 */
	public java.lang.Integer getTime() {
		return (java.lang.Integer) getValue(16);
	}

	/**
	 * Setter for <code>chatdb.chat_material.type</code>.
	 */
	public void setType(java.lang.Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.type</code>.
	 */
	public java.lang.Integer getType() {
		return (java.lang.Integer) getValue(17);
	}

	/**
	 * Setter for <code>chatdb.chat_material.height</code>.
	 */
	public void setHeight(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.height</code>.
	 */
	public java.lang.Integer getHeight() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>chatdb.chat_material.width</code>.
	 */
	public void setWidth(java.lang.Integer value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.width</code>.
	 */
	public java.lang.Integer getWidth() {
		return (java.lang.Integer) getValue(19);
	}

	/**
	 * Setter for <code>chatdb.chat_material.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>chatdb.chat_material.expires_time</code>.
	 */
	public void setExpiresTime(java.lang.Long value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>chatdb.chat_material.expires_time</code>.
	 */
	public java.lang.Long getExpiresTime() {
		return (java.lang.Long) getValue(21);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record22 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row22) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row22) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.COST_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.ERRCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.ERRMSG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.LAST_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.MATERIAL_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.MEDIA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field13() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.MEDIA_SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.CLASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field17() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field18() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field19() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.HEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field20() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.WIDTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field21() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field22() {
		return com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.EXPIRES_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getCostTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getErrcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getErrmsg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getLastUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getMaterialType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getMediaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value13() {
		return getMediaSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getClass_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value17() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value18() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value19() {
		return getHeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value20() {
		return getWidth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value21() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value22() {
		return getExpiresTime();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChatMaterialRecord
	 */
	public ChatMaterialRecord() {
		super(com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL);
	}

	/**
	 * Create a detached, initialised ChatMaterialRecord
	 */
	public ChatMaterialRecord(java.lang.Long id, java.lang.Long version, java.lang.Long accountId, java.lang.Long costTime, java.sql.Timestamp createTime, java.sql.Timestamp dateCreated, java.lang.String description, java.lang.Integer errcode, java.lang.String errmsg, java.sql.Timestamp lastUpdated, java.lang.Integer materialType, java.lang.String mediaId, java.lang.Long mediaSize, java.lang.String name, java.lang.String path, java.lang.String class_, java.lang.Integer time, java.lang.Integer type, java.lang.Integer height, java.lang.Integer width, java.lang.String title, java.lang.Long expiresTime) {
		super(com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL);

		setValue(0, id);
		setValue(1, version);
		setValue(2, accountId);
		setValue(3, costTime);
		setValue(4, createTime);
		setValue(5, dateCreated);
		setValue(6, description);
		setValue(7, errcode);
		setValue(8, errmsg);
		setValue(9, lastUpdated);
		setValue(10, materialType);
		setValue(11, mediaId);
		setValue(12, mediaSize);
		setValue(13, name);
		setValue(14, path);
		setValue(15, class_);
		setValue(16, time);
		setValue(17, type);
		setValue(18, height);
		setValue(19, width);
		setValue(20, title);
		setValue(21, expiresTime);
	}
}
