/**
 * This class is generated by jOOQ
 */
package com.trunksoft.chat.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMemberRecord extends org.jooq.impl.UpdatableRecordImpl<com.trunksoft.chat.jooq.tables.records.ChatMemberRecord> {

	private static final long serialVersionUID = 2127935860;

	/**
	 * Setter for <code>chatdb.chat_member.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>chatdb.chat_member.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>chatdb.chat_member.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.account_id</code>.
	 */
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>chatdb.chat_member.address</code>.
	 */
	public void setAddress(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.address</code>.
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>chatdb.chat_member.age</code>.
	 */
	public void setAge(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.age</code>.
	 */
	public java.lang.Integer getAge() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>chatdb.chat_member.birthday</code>.
	 */
	public void setBirthday(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.birthday</code>.
	 */
	public java.sql.Timestamp getBirthday() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>chatdb.chat_member.city</code>.
	 */
	public void setCity(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>chatdb.chat_member.country</code>.
	 */
	public void setCountry(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.country</code>.
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>chatdb.chat_member.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>chatdb.chat_member.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>chatdb.chat_member.grade_id</code>.
	 */
	public void setGradeId(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.grade_id</code>.
	 */
	public java.lang.Long getGradeId() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>chatdb.chat_member.group_id</code>.
	 */
	public void setGroupId(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.group_id</code>.
	 */
	public java.lang.Long getGroupId() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>chatdb.chat_member.headimgurl</code>.
	 */
	public void setHeadimgurl(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.headimgurl</code>.
	 */
	public java.lang.String getHeadimgurl() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>chatdb.chat_member.language</code>.
	 */
	public void setLanguage(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.language</code>.
	 */
	public java.lang.String getLanguage() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>chatdb.chat_member.last_updated</code>.
	 */
	public void setLastUpdated(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.last_updated</code>.
	 */
	public java.sql.Timestamp getLastUpdated() {
		return (java.sql.Timestamp) getValue(14);
	}

	/**
	 * Setter for <code>chatdb.chat_member.location_id</code>.
	 */
	public void setLocationId(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.location_id</code>.
	 */
	public java.lang.Long getLocationId() {
		return (java.lang.Long) getValue(15);
	}

	/**
	 * Setter for <code>chatdb.chat_member.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>chatdb.chat_member.nick_name</code>.
	 */
	public void setNickName(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.nick_name</code>.
	 */
	public java.lang.String getNickName() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>chatdb.chat_member.no</code>.
	 */
	public void setNo(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.no</code>.
	 */
	public java.lang.Integer getNo() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>chatdb.chat_member.open_id</code>.
	 */
	public void setOpenId(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.open_id</code>.
	 */
	public java.lang.String getOpenId() {
		return (java.lang.String) getValue(19);
	}

	/**
	 * Setter for <code>chatdb.chat_member.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>chatdb.chat_member.province</code>.
	 */
	public void setProvince(java.lang.String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.province</code>.
	 */
	public java.lang.String getProvince() {
		return (java.lang.String) getValue(21);
	}

	/**
	 * Setter for <code>chatdb.chat_member.qq</code>.
	 */
	public void setQq(java.lang.String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.qq</code>.
	 */
	public java.lang.String getQq() {
		return (java.lang.String) getValue(22);
	}

	/**
	 * Setter for <code>chatdb.chat_member.sex</code>.
	 */
	public void setSex(java.lang.Integer value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.sex</code>.
	 */
	public java.lang.Integer getSex() {
		return (java.lang.Integer) getValue(23);
	}

	/**
	 * Setter for <code>chatdb.chat_member.subscribe</code>.
	 */
	public void setSubscribe(java.lang.Boolean value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.subscribe</code>.
	 */
	public java.lang.Boolean getSubscribe() {
		return (java.lang.Boolean) getValue(24);
	}

	/**
	 * Setter for <code>chatdb.chat_member.subscribe_time</code>.
	 */
	public void setSubscribeTime(java.sql.Timestamp value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.subscribe_time</code>.
	 */
	public java.sql.Timestamp getSubscribeTime() {
		return (java.sql.Timestamp) getValue(25);
	}

	/**
	 * Setter for <code>chatdb.chat_member.unionid</code>.
	 */
	public void setUnionid(java.lang.String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.unionid</code>.
	 */
	public java.lang.String getUnionid() {
		return (java.lang.String) getValue(26);
	}

	/**
	 * Setter for <code>chatdb.chat_member.weixin</code>.
	 */
	public void setWeixin(java.lang.String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.weixin</code>.
	 */
	public java.lang.String getWeixin() {
		return (java.lang.String) getValue(27);
	}

	/**
	 * Setter for <code>chatdb.chat_member.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(28);
	}

	/**
	 * Setter for <code>chatdb.chat_member.postcode</code>.
	 */
	public void setPostcode(java.lang.String value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member.postcode</code>.
	 */
	public java.lang.String getPostcode() {
		return (java.lang.String) getValue(29);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChatMemberRecord
	 */
	public ChatMemberRecord() {
		super(com.trunksoft.chat.jooq.tables.ChatMember.CHAT_MEMBER);
	}

	/**
	 * Create a detached, initialised ChatMemberRecord
	 */
	public ChatMemberRecord(java.lang.Long id, java.lang.Long version, java.lang.Long accountId, java.lang.String address, java.lang.Integer age, java.sql.Timestamp birthday, java.lang.String city, java.lang.String country, java.sql.Timestamp dateCreated, java.lang.String email, java.lang.Long gradeId, java.lang.Long groupId, java.lang.String headimgurl, java.lang.String language, java.sql.Timestamp lastUpdated, java.lang.Long locationId, java.lang.String name, java.lang.String nickName, java.lang.Integer no, java.lang.String openId, java.lang.String phone, java.lang.String province, java.lang.String qq, java.lang.Integer sex, java.lang.Boolean subscribe, java.sql.Timestamp subscribeTime, java.lang.String unionid, java.lang.String weixin, java.lang.String description, java.lang.String postcode) {
		super(com.trunksoft.chat.jooq.tables.ChatMember.CHAT_MEMBER);

		setValue(0, id);
		setValue(1, version);
		setValue(2, accountId);
		setValue(3, address);
		setValue(4, age);
		setValue(5, birthday);
		setValue(6, city);
		setValue(7, country);
		setValue(8, dateCreated);
		setValue(9, email);
		setValue(10, gradeId);
		setValue(11, groupId);
		setValue(12, headimgurl);
		setValue(13, language);
		setValue(14, lastUpdated);
		setValue(15, locationId);
		setValue(16, name);
		setValue(17, nickName);
		setValue(18, no);
		setValue(19, openId);
		setValue(20, phone);
		setValue(21, province);
		setValue(22, qq);
		setValue(23, sex);
		setValue(24, subscribe);
		setValue(25, subscribeTime);
		setValue(26, unionid);
		setValue(27, weixin);
		setValue(28, description);
		setValue(29, postcode);
	}
}
