/**
 * This class is generated by jOOQ
 */
package com.trunksoft.chat.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMaterial extends org.jooq.impl.TableImpl<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord> {

	private static final long serialVersionUID = 1742439088;

	/**
	 * The singleton instance of <code>chatdb.chat_material</code>
	 */
	public static final com.trunksoft.chat.jooq.tables.ChatMaterial CHAT_MATERIAL = new com.trunksoft.chat.jooq.tables.ChatMaterial();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord> getRecordType() {
		return com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord.class;
	}

	/**
	 * The column <code>chatdb.chat_material.id</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.version</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.account_id</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.cost_time</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> COST_TIME = createField("cost_time", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>chatdb.chat_material.create_time</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>chatdb.chat_material.date_created</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.sql.Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.description</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_material.errcode</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Integer> ERRCODE = createField("errcode", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chatdb.chat_material.errmsg</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> ERRMSG = createField("errmsg", org.jooq.impl.SQLDataType.VARCHAR.length(2000), this);

	/**
	 * The column <code>chatdb.chat_material.last_updated</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.sql.Timestamp> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.material_type</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Integer> MATERIAL_TYPE = createField("material_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.media_id</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> MEDIA_ID = createField("media_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_material.media_size</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> MEDIA_SIZE = createField("media_size", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.name</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_material.path</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_material.class</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> CLASS = createField("class", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>chatdb.chat_material.time</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Integer> TIME = createField("time", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chatdb.chat_material.type</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chatdb.chat_material.height</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chatdb.chat_material.width</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Integer> WIDTH = createField("width", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chatdb.chat_material.title</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_material.expires_time</code>.
	 */
	public final org.jooq.TableField<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> EXPIRES_TIME = createField("expires_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>chatdb.chat_material</code> table reference
	 */
	public ChatMaterial() {
		super("chat_material", com.trunksoft.chat.jooq.Chatdb.CHATDB);
	}

	/**
	 * Create an aliased <code>chatdb.chat_material</code> table reference
	 */
	public ChatMaterial(java.lang.String alias) {
		super(alias, com.trunksoft.chat.jooq.Chatdb.CHATDB, com.trunksoft.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> getIdentity() {
		return com.trunksoft.chat.jooq.Keys.IDENTITY_CHAT_MATERIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord> getPrimaryKey() {
		return com.trunksoft.chat.jooq.Keys.KEY_CHAT_MATERIAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.trunksoft.chat.jooq.tables.records.ChatMaterialRecord>>asList(com.trunksoft.chat.jooq.Keys.KEY_CHAT_MATERIAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.trunksoft.chat.jooq.tables.ChatMaterial as(java.lang.String alias) {
		return new com.trunksoft.chat.jooq.tables.ChatMaterial(alias);
	}
}
