/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMessageTemplate extends org.jooq.impl.TableImpl<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> {

	private static final long serialVersionUID = -1691693077;

	/**
	 * The singleton instance of <code>chatdb.chat_message_template</code>
	 */
	public static final com.seecent.chat.jooq.tables.ChatMessageTemplate CHAT_MESSAGE_TEMPLATE = new com.seecent.chat.jooq.tables.ChatMessageTemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> getRecordType() {
		return com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord.class;
	}

	/**
	 * The column <code>chatdb.chat_message_template.id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.version</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.account_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.content</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.date_created</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.sql.Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.last_updated</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.sql.Timestamp> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.primary_industry</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.String> PRIMARY_INDUSTRY = createField("primary_industry", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_message_template.sample</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.String> SAMPLE = createField("sample", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this);

	/**
	 * The column <code>chatdb.chat_message_template.secondary_industry</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.String> SECONDARY_INDUSTRY = createField("secondary_industry", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_message_template.template_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.String> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.title</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>chatdb.chat_message_template.type</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>chatdb.chat_message_template</code> table reference
	 */
	public ChatMessageTemplate() {
		super("chat_message_template", com.seecent.chat.jooq.Chatdb.CHATDB);
	}

	/**
	 * Create an aliased <code>chatdb.chat_message_template</code> table reference
	 */
	public ChatMessageTemplate(java.lang.String alias) {
		super(alias, com.seecent.chat.jooq.Chatdb.CHATDB, com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Long> getIdentity() {
		return com.seecent.chat.jooq.Keys.IDENTITY_CHAT_MESSAGE_TEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> getPrimaryKey() {
		return com.seecent.chat.jooq.Keys.KEY_CHAT_MESSAGE_TEMPLATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord>>asList(com.seecent.chat.jooq.Keys.KEY_CHAT_MESSAGE_TEMPLATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.seecent.chat.jooq.tables.ChatMessageTemplate as(java.lang.String alias) {
		return new com.seecent.chat.jooq.tables.ChatMessageTemplate(alias);
	}
}
