/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatTemplateMessage extends org.jooq.impl.TableImpl<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord> {

	private static final long serialVersionUID = 1810540837;

	/**
	 * The singleton instance of <code>chatdb.chat_template_message</code>
	 */
	public static final com.seecent.chat.jooq.tables.ChatTemplateMessage CHAT_TEMPLATE_MESSAGE = new com.seecent.chat.jooq.tables.ChatTemplateMessage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord> getRecordType() {
		return com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord.class;
	}

	/**
	 * The column <code>chatdb.chat_template_message.id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.account_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.content</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(4000).nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.data_json</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.String> DATA_JSON = createField("data_json", org.jooq.impl.SQLDataType.VARCHAR.length(4000).nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.date_created</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.sql.Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.errcode</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Integer> ERRCODE = createField("errcode", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.errmsg</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.String> ERRMSG = createField("errmsg", org.jooq.impl.SQLDataType.VARCHAR.length(2000), this);

	/**
	 * The column <code>chatdb.chat_template_message.from_user_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> FROM_USER_ID = createField("from_user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>chatdb.chat_template_message.last_updated</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.sql.Timestamp> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.msg_time</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> MSG_TIME = createField("msg_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.msgid</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> MSGID = createField("msgid", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>chatdb.chat_template_message.status</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.template_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.to_user_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> TO_USER_ID = createField("to_user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>chatdb.chat_template_message.type</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_template_message.url</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>chatdb.chat_template_message</code> table reference
	 */
	public ChatTemplateMessage() {
		super("chat_template_message", com.seecent.chat.jooq.Chatdb.CHATDB);
	}

	/**
	 * Create an aliased <code>chatdb.chat_template_message</code> table reference
	 */
	public ChatTemplateMessage(java.lang.String alias) {
		super(alias, com.seecent.chat.jooq.Chatdb.CHATDB, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> getIdentity() {
		return com.seecent.chat.jooq.Keys.IDENTITY_CHAT_TEMPLATE_MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord> getPrimaryKey() {
		return com.seecent.chat.jooq.Keys.KEY_CHAT_TEMPLATE_MESSAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord>>asList(com.seecent.chat.jooq.Keys.KEY_CHAT_TEMPLATE_MESSAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, ?>>asList(com.seecent.chat.jooq.Keys.FKB55F434971B2504F, com.seecent.chat.jooq.Keys.FKB55F434982236D21, com.seecent.chat.jooq.Keys.FKB55F434910AE620);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.seecent.chat.jooq.tables.ChatTemplateMessage as(java.lang.String alias) {
		return new com.seecent.chat.jooq.tables.ChatTemplateMessage(alias);
	}
}
