/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMemberGroup extends org.jooq.impl.TableImpl<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> {

	private static final long serialVersionUID = 877512405;

	/**
	 * The singleton instance of <code>chatdb.chat_member_group</code>
	 */
	public static final com.seecent.chat.jooq.tables.ChatMemberGroup CHAT_MEMBER_GROUP = new com.seecent.chat.jooq.tables.ChatMemberGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> getRecordType() {
		return com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord.class;
	}

	/**
	 * The column <code>chatdb.chat_member_group.id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_member_group.version</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_member_group.account_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_member_group.date_created</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.sql.Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_member_group.description</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>chatdb.chat_member_group.group_id</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_member_group.last_updated</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.sql.Timestamp> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chatdb.chat_member_group.name</code>.
	 */
	public final org.jooq.TableField<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>chatdb.chat_member_group</code> table reference
	 */
	public ChatMemberGroup() {
		super("chat_member_group", com.seecent.chat.jooq.Chatdb.CHATDB);
	}

	/**
	 * Create an aliased <code>chatdb.chat_member_group</code> table reference
	 */
	public ChatMemberGroup(java.lang.String alias) {
		super(alias, com.seecent.chat.jooq.Chatdb.CHATDB, com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> getIdentity() {
		return com.seecent.chat.jooq.Keys.IDENTITY_CHAT_MEMBER_GROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> getPrimaryKey() {
		return com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_GROUP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord>>asList(com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_GROUP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.seecent.chat.jooq.tables.ChatMemberGroup as(java.lang.String alias) {
		return new com.seecent.chat.jooq.tables.ChatMemberGroup(alias);
	}
}
