/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMemberGroupRecord extends org.jooq.impl.UpdatableRecordImpl<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> implements org.jooq.Record8<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = -634481783;

	/**
	 * Setter for <code>chatdb.chat_member_group.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.account_id</code>.
	 */
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.group_id</code>.
	 */
	public void setGroupId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.group_id</code>.
	 */
	public java.lang.Long getGroupId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.last_updated</code>.
	 */
	public void setLastUpdated(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.last_updated</code>.
	 */
	public java.sql.Timestamp getLastUpdated() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>chatdb.chat_member_group.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chatdb.chat_member_group.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.LAST_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getLastUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getName();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChatMemberGroupRecord
	 */
	public ChatMemberGroupRecord() {
		super(com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP);
	}

	/**
	 * Create a detached, initialised ChatMemberGroupRecord
	 */
	public ChatMemberGroupRecord(java.lang.Long id, java.lang.Long version, java.lang.Long accountId, java.sql.Timestamp dateCreated, java.lang.String description, java.lang.Long groupId, java.sql.Timestamp lastUpdated, java.lang.String name) {
		super(com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP);

		setValue(0, id);
		setValue(1, version);
		setValue(2, accountId);
		setValue(3, dateCreated);
		setValue(4, description);
		setValue(5, groupId);
		setValue(6, lastUpdated);
		setValue(7, name);
	}
}
