/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chatdb extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1118141698;

	/**
	 * The singleton instance of <code>chatdb</code>
	 */
	public static final Chatdb CHATDB = new Chatdb();

	/**
	 * No further instances allowed
	 */
	private Chatdb() {
		super("chatdb");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE,
			com.seecent.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL,
			com.seecent.chat.jooq.tables.ChatMaterialTag.CHAT_MATERIAL_TAG,
			com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER,
			com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP,
			com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE,
			com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE);
	}
}
