/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>chatdb</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord, java.lang.Long> IDENTITY_CHAT_CHAT_MESSAGE = Identities0.IDENTITY_CHAT_CHAT_MESSAGE;
	public static final org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> IDENTITY_CHAT_MATERIAL = Identities0.IDENTITY_CHAT_MATERIAL;
	public static final org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMemberRecord, java.lang.Long> IDENTITY_CHAT_MEMBER = Identities0.IDENTITY_CHAT_MEMBER;
	public static final org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> IDENTITY_CHAT_MEMBER_GROUP = Identities0.IDENTITY_CHAT_MEMBER_GROUP;
	public static final org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Long> IDENTITY_CHAT_MESSAGE_TEMPLATE = Identities0.IDENTITY_CHAT_MESSAGE_TEMPLATE;
	public static final org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> IDENTITY_CHAT_TEMPLATE_MESSAGE = Identities0.IDENTITY_CHAT_TEMPLATE_MESSAGE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord> KEY_CHAT_CHAT_MESSAGE_PRIMARY = UniqueKeys0.KEY_CHAT_CHAT_MESSAGE_PRIMARY;
	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMaterialRecord> KEY_CHAT_MATERIAL_PRIMARY = UniqueKeys0.KEY_CHAT_MATERIAL_PRIMARY;
	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberRecord> KEY_CHAT_MEMBER_PRIMARY = UniqueKeys0.KEY_CHAT_MEMBER_PRIMARY;
	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberRecord> KEY_CHAT_MEMBER_ACCOUNT_ID = UniqueKeys0.KEY_CHAT_MEMBER_ACCOUNT_ID;
	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> KEY_CHAT_MEMBER_GROUP_PRIMARY = UniqueKeys0.KEY_CHAT_MEMBER_GROUP_PRIMARY;
	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> KEY_CHAT_MESSAGE_TEMPLATE_PRIMARY = UniqueKeys0.KEY_CHAT_MESSAGE_TEMPLATE_PRIMARY;
	public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord> KEY_CHAT_TEMPLATE_MESSAGE_PRIMARY = UniqueKeys0.KEY_CHAT_TEMPLATE_MESSAGE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB72167A771B2504F = ForeignKeys0.FKB72167A771B2504F;
	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB72167A710AE620 = ForeignKeys0.FKB72167A710AE620;
	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatMaterialTagRecord, com.seecent.chat.jooq.tables.records.ChatMaterialRecord> FK3E206E09424A9A0C = ForeignKeys0.FK3E206E09424A9A0C;
	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatMemberRecord, com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> FK73700161783EC85 = ForeignKeys0.FK73700161783EC85;
	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB55F434971B2504F = ForeignKeys0.FKB55F434971B2504F;
	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> FKB55F434982236D21 = ForeignKeys0.FKB55F434982236D21;
	public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB55F434910AE620 = ForeignKeys0.FKB55F434910AE620;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord, java.lang.Long> IDENTITY_CHAT_CHAT_MESSAGE = createIdentity(com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE, com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE.ID);
		public static org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMaterialRecord, java.lang.Long> IDENTITY_CHAT_MATERIAL = createIdentity(com.seecent.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL, com.seecent.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.ID);
		public static org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMemberRecord, java.lang.Long> IDENTITY_CHAT_MEMBER = createIdentity(com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER, com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER.ID);
		public static org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord, java.lang.Long> IDENTITY_CHAT_MEMBER_GROUP = createIdentity(com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP, com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.ID);
		public static org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord, java.lang.Long> IDENTITY_CHAT_MESSAGE_TEMPLATE = createIdentity(com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE, com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.ID);
		public static org.jooq.Identity<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, java.lang.Long> IDENTITY_CHAT_TEMPLATE_MESSAGE = createIdentity(com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord> KEY_CHAT_CHAT_MESSAGE_PRIMARY = createUniqueKey(com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE, com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE.ID);
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMaterialRecord> KEY_CHAT_MATERIAL_PRIMARY = createUniqueKey(com.seecent.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL, com.seecent.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL.ID);
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberRecord> KEY_CHAT_MEMBER_PRIMARY = createUniqueKey(com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER, com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER.ID);
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberRecord> KEY_CHAT_MEMBER_ACCOUNT_ID = createUniqueKey(com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER, com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER.ACCOUNT_ID, com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER.NO);
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> KEY_CHAT_MEMBER_GROUP_PRIMARY = createUniqueKey(com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP, com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP.ID);
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> KEY_CHAT_MESSAGE_TEMPLATE_PRIMARY = createUniqueKey(com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE, com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE.ID);
		public static final org.jooq.UniqueKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord> KEY_CHAT_TEMPLATE_MESSAGE_PRIMARY = createUniqueKey(com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB72167A771B2504F = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_PRIMARY, com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE, com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE.FROM_USER_ID);
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatChatMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB72167A710AE620 = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_PRIMARY, com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE, com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE.TO_USER_ID);
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatMaterialTagRecord, com.seecent.chat.jooq.tables.records.ChatMaterialRecord> FK3E206E09424A9A0C = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MATERIAL_PRIMARY, com.seecent.chat.jooq.tables.ChatMaterialTag.CHAT_MATERIAL_TAG, com.seecent.chat.jooq.tables.ChatMaterialTag.CHAT_MATERIAL_TAG.MATERIAL_ID);
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatMemberRecord, com.seecent.chat.jooq.tables.records.ChatMemberGroupRecord> FK73700161783EC85 = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_GROUP_PRIMARY, com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER, com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER.GROUP_ID);
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB55F434971B2504F = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_PRIMARY, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.FROM_USER_ID);
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, com.seecent.chat.jooq.tables.records.ChatMessageTemplateRecord> FKB55F434982236D21 = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MESSAGE_TEMPLATE_PRIMARY, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.TEMPLATE_ID);
		public static final org.jooq.ForeignKey<com.seecent.chat.jooq.tables.records.ChatTemplateMessageRecord, com.seecent.chat.jooq.tables.records.ChatMemberRecord> FKB55F434910AE620 = createForeignKey(com.seecent.chat.jooq.Keys.KEY_CHAT_MEMBER_PRIMARY, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE, com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE.TO_USER_ID);
	}
}
