/**
 * This class is generated by jOOQ
 */
package com.seecent.chat.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in chatdb
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table chatdb.chat_chat_message
	 */
	public static final com.seecent.chat.jooq.tables.ChatChatMessage CHAT_CHAT_MESSAGE = com.seecent.chat.jooq.tables.ChatChatMessage.CHAT_CHAT_MESSAGE;

	/**
	 * The table chatdb.chat_material
	 */
	public static final com.seecent.chat.jooq.tables.ChatMaterial CHAT_MATERIAL = com.seecent.chat.jooq.tables.ChatMaterial.CHAT_MATERIAL;

	/**
	 * The table chatdb.chat_material_tag
	 */
	public static final com.seecent.chat.jooq.tables.ChatMaterialTag CHAT_MATERIAL_TAG = com.seecent.chat.jooq.tables.ChatMaterialTag.CHAT_MATERIAL_TAG;

	/**
	 * The table chatdb.chat_member
	 */
	public static final com.seecent.chat.jooq.tables.ChatMember CHAT_MEMBER = com.seecent.chat.jooq.tables.ChatMember.CHAT_MEMBER;

	/**
	 * The table chatdb.chat_member_group
	 */
	public static final com.seecent.chat.jooq.tables.ChatMemberGroup CHAT_MEMBER_GROUP = com.seecent.chat.jooq.tables.ChatMemberGroup.CHAT_MEMBER_GROUP;

	/**
	 * The table chatdb.chat_message_template
	 */
	public static final com.seecent.chat.jooq.tables.ChatMessageTemplate CHAT_MESSAGE_TEMPLATE = com.seecent.chat.jooq.tables.ChatMessageTemplate.CHAT_MESSAGE_TEMPLATE;

	/**
	 * The table chatdb.chat_template_message
	 */
	public static final com.seecent.chat.jooq.tables.ChatTemplateMessage CHAT_TEMPLATE_MESSAGE = com.seecent.chat.jooq.tables.ChatTemplateMessage.CHAT_TEMPLATE_MESSAGE;
}
